F2GTraining/Controllers/EntrenamientosController.cs
using F2GTraining.Extensions;
using F2GTraining.Filters;
using ModelsF2GTraining;
using Microsoft.AspNetCore.Mvc;
using F2GTraining.Services;

namespace F2GTraining.Controllers
{
    public class EntrenamientosController : Controller
    {
        private ServiceAPIF2GTraining service;

        public EntrenamientosController(ServiceAPIF2GTraining service)
        {
            this.service = service;
        }

        [AuthorizeUsers]
        public async Task<IActionResult> ListaSesiones(int idequipo)
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst("IDUSUARIO").Value.ToString());
            string token = HttpContext.Session.GetString("TOKEN");

            Equipo equipo = await this.service.GetEquipo(token,idequipo);

            if (equipo == null || equipo.IdUsuario != idusuario)
            {
                return RedirectToAction("MenuEquipo", "Equipos");
            }
            else
            {
                ViewData["IDEQUIPO"] = idequipo;
                ViewData["NOMBREEQUIPO"] = equipo.Nombre;
                return View(await this.service.GetEntrenamientosEquipo(token,idequipo));
            }

        }

        [AuthorizeUsers]
        [HttpPost]
        public async Task<IActionResult> ListaSesiones(int idequipo, string nombre)
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst("IDUSUARIO").Value.ToString());
            string token = HttpContext.Session.GetString("TOKEN");

            Equipo equipo = await this.service.GetEquipo(token,idequipo);

            if (equipo == null || equipo.IdUsuario != idusuario)
            {
                return RedirectToAction("MenuEquipo", "Equipos");
            }
            else
            {
                await this.service.InsertEntrenamiento(token,idequipo, nombre);
                return RedirectToAction("ListaSesiones", new { idequipo = idequipo });
            }

        }

        [AuthorizeUsers]
        public async Task<IActionResult> EliminaEntrenamiento(int identrenamiento, int idequipo)
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst("IDUSUARIO").Value.ToString());
            string token = HttpContext.Session.GetString("TOKEN");

            Equipo equipo = await this.service.GetEquipo(token,idequipo);

            if (equipo == null || equipo.IdUsuario != idusuario)
            {
                return RedirectToAction("MenuEquipo", "Equipos");
            }
            else
            {
                await this.service.DeleteEntrenamiento(token,identrenamiento);
                return RedirectToAction("ListaSesiones", new { idequipo = idequipo });
            }

        }

        [AuthorizeUsers]
        public async Task<IActionResult> VistaEntrenamiento(int identrenamiento, int idequipo)
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst("IDUSUARIO").Value.ToString());
            string token = HttpContext.Session.GetString("TOKEN");

            Equipo equipo = await this.service.GetEquipo(token,idequipo);

            if (equipo == null || equipo.IdUsuario != idusuario)
            {
                return RedirectToAction("MenuEquipo", "Equipos");
            }

            Entrenamiento entrena = await this.service.GetEntrenamiento(token,identrenamiento);
            List<Jugador> jugadoresequipo;

            if (entrena.Activo == false && entrena.FechaFin == null)
            {
                jugadoresequipo = await this.service.GetJugadoresEquipo(token,idequipo);
            }
            else if (entrena.Activo == false && entrena.FechaFin != null)
            {
                jugadoresequipo = await this.service.GetJugadoresXSesion(token,identrenamiento);
                List<JugadorEntrenamiento> notas = await this.service.GetNotasSesion(token,identrenamiento);
                ViewData["NOTAS"] = notas;
            }
            else
            {
                jugadoresequipo = await this.service.GetJugadoresXSesion(token,identrenamiento);
            }
            
            ViewData["JUGADORES"] = jugadoresequipo;
            ViewData["IDEQUIPO"] = idequipo;
            ViewData["IDENTRENAMIENTO"] = identrenamiento;

            return View(entrena);
        }

        [AuthorizeUsers]
        [HttpPost]
        public async Task<IActionResult> VistaEntrenamiento(int identrenamiento, int idequipo, List<int> seleccionados, List<int> valoraciones)
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst("IDUSUARIO").Value.ToString());
            string token = HttpContext.Session.GetString("TOKEN");

            Equipo equipo = await this.service.GetEquipo(token,idequipo);

            if (equipo == null || equipo.IdUsuario != idusuario)
            {
                return RedirectToAction("MenuEquipo", "Equipos");
            }

            Entrenamiento entrena = await this.service.GetEntrenamiento(token,identrenamiento);
            List<Jugador> jugadoresequipo;

            if (entrena.Activo == false)
            {
                //AQUI VA EL CODIGO PARA AÑADIRLO A LA AUXILIAR DE ENTRENAMIENTOJUGADOR
                await this.service.AniadirJugadoresSesion(token,identrenamiento,seleccionados);
                jugadoresequipo = await this.service.GetJugadoresXSesion(token,identrenamiento);
            }
            else 
            {
                jugadoresequipo = await this.service.GetJugadoresXSesion(token,identrenamiento);
                //AQUI HAY QUE HACER PROCEDURE PARA ASIGNAR NOTAS A CADA JUGADOR APUNTADO
                await this.service.AniadirPuntuacionesEntrenamiento(token, identrenamiento, seleccionados, valoraciones);

                List<JugadorEntrenamiento> notas = await this.service.GetNotasSesion(token,identrenamiento);
                ViewData["NOTAS"] = notas;
            }

            ViewData["JUGADORES"] = jugadoresequipo;
            ViewData["IDEQUIPO"] = idequipo;
            ViewData["IDENTRENAMIENTO"] = identrenamiento;

            return RedirectToAction("VistaEntrenamiento", new { idequipo = idequipo, identrenamiento = identrenamiento });

        }
    }
}

F2GTraining/Controllers/JugadoresController.cs
using F2GTraining.Extensions;
using F2GTraining.Filters;
using ModelsF2GTraining;
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using F2GTraining.Services;

namespace F2GTraining.Controllers
{
    public class JugadoresController : Controller
    {
        private ServiceAPIF2GTraining service;

        public JugadoresController(ServiceAPIF2GTraining service)
        {
            this.service = service;
        }

        [AuthorizeUsers]
        public async Task<IActionResult> CrearJugador(int idequipo)
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst("IDUSUARIO").Value.ToString());
            string token = HttpContext.Session.GetString("TOKEN");

            Equipo equipo = await this.service.GetEquipo(token,idequipo);

            if (equipo == null || equipo.IdUsuario != idusuario)
            {
                return RedirectToAction("MenuEquipo", "Equipos");
            }
            else
            {
                ViewData["IDEQUIPO"] = equipo.IdEquipo;
                ViewData["NOMBRE"] = equipo.Nombre;
                return View(await this.service.GetPosiciones());
            }

        }

        [AuthorizeUsers]
        [HttpPost]
        public async Task<IActionResult> CrearJugador(int idequipo, int idposicion, string nombre, int dorsal, int edad, int peso, int altura)
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst("IDUSUARIO").Value.ToString());
            string token = HttpContext.Session.GetString("TOKEN");

            Equipo equipo = await this.service.GetEquipo(token,idequipo);

            if (equipo != null || equipo.IdUsuario == idusuario)
            {
                Jugador jug = new Jugador
                {
                    IdEquipo = idequipo,
                    IdPosicion = idposicion,
                    Nombre = nombre,
                    Dorsal = dorsal,
                    Edad = edad,
                    Peso = peso,
                    Altura = altura
                };

                await this.service.InsertJugador(token, jug);
            }

            return RedirectToAction("MenuEquipo", "Equipos");

        }

        [AuthorizeUsers]
        public async Task<IActionResult> DeleteJugador(int idjugador)
        {
            string token = HttpContext.Session.GetString("TOKEN");

            List<Jugador> jugadoresUser = await this.service.GetJugadoresUsuario(token);
            Jugador jugBorrar = await this.service.GetJugadorID(token, idjugador);

            foreach (Jugador jugador in jugadoresUser)
            {
                if (jugador.IdJugador == jugBorrar.IdJugador)
                {
                    await this.service.DeleteJugador(token, idjugador);
                }
            }

            return RedirectToAction("MenuEquipo", "Equipos");

        }

        [AuthorizeUsers]
        public async Task<IActionResult> GraficaJugador(int idjugador)
        {
            string token = HttpContext.Session.GetString("TOKEN");

            List<Jugador> jugadoresUser = await this.service.GetJugadoresUsuario(token);
            Jugador jugMostrar = await this.service.GetJugadorID(token,idjugador);

            foreach (Jugador jugador in jugadoresUser)
            {
                if (jugador.IdJugador == jugMostrar.IdJugador)
                {
                    EstadisticaJugador stats = await this.service.GetEstadisticasJugador(token, idjugador);
                    ViewData["ESTADISTICAS"] = stats;
                    return View(jugMostrar);
                }
            }
            
            return RedirectToAction("MenuEquipo", "Equipos");

        }

        [AuthorizeUsers]
        public async Task<IActionResult> _PartialJugadoresEquipo(int idequipo)
        {
            string token = HttpContext.Session.GetString("TOKEN");
            return PartialView(await this.service.GetJugadoresEquipo(token,idequipo));
        }

        public async Task<IActionResult> GraficaComoPDF(int idjugador)
        {
            string token = HttpContext.Session.GetString("TOKEN");

            List<Jugador> jugadoresUser = await this.service.GetJugadoresUsuario(token);
            Jugador jugGrafica = await this.service.GetJugadorID(token,idjugador);

            foreach (Jugador jugador in jugadoresUser)
            {
                if (jugador.IdJugador == jugGrafica.IdJugador)
                {
                    Equipo equipo = await this.service.GetEquipo(token, jugGrafica.IdEquipo);
                    EstadisticaJugador stats = await this.service.GetEstadisticasJugador(token, idjugador);
                    PDFJugador modeloPDF = new PDFJugador
                    {
                        Jugador = jugGrafica,
                        Estadisticas = stats,
                        EquipoJugador = equipo
                    };

                    return new ViewAsPdf(modeloPDF);
                }
            }

            return RedirectToAction("MenuEquipo", "Equipos");        
        }
    }
}

F2GTraining/Controllers/UsuariosController.cs
using F2GTraining.Extensions;
using F2GTraining.Filters;
using ModelsF2GTraining;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using F2GTraining.Services;

namespace F2GTraining.Controllers
{
    public class UsuariosController : Controller
    {
        private ServiceAPIF2GTraining service;

        public UsuariosController(ServiceAPIF2GTraining service)
        {
            this.service = service;
        }


        public IActionResult InicioSesion()
        {
            if (HttpContext.User.FindFirst("IDUSUARIO") != null)
            {
                return RedirectToAction("MenuEquipo","Equipos");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> InicioSesion(string usuario, string contrasenha)
        {
            string token = await this.service.GetTokenAsync(usuario, contrasenha);

            if (token != null)
            {
                Usuario user = await this.service.GetUsuarioAsync(token);

                ClaimsIdentity identity = new ClaimsIdentity
                (CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);

                Claim claimName = new Claim(ClaimTypes.Name, user.Nombre);
                identity.AddClaim(claimName);

                Claim claimId = new Claim("IDUSUARIO", user.IdUsuario.ToString());
                identity.AddClaim(claimId);

                ClaimsPrincipal userPrincipal =
                    new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync
                    (CookieAuthenticationDefaults.AuthenticationScheme
                    , userPrincipal, new AuthenticationProperties
                    {
                        ExpiresUtc = DateTime.Now.AddHours(12)
                    });

                HttpContext.Session.SetString("TOKEN", token);
                return RedirectToAction("MenuEquipo", "Equipos");

            }
            else
            {
                ViewData["ERROR"] = "ERROR: Credenciales de acceso erróneas";
                return View();
            }

        }

        public IActionResult RegistroUsuario()
        {
            if (HttpContext.User.FindFirst("IDUSUARIO") != null)
            {
                return RedirectToAction("MenuEquipo", "Equipos");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegistroUsuario(string usuario, string contrasenha, string correo, int telefono)
        {
            if (HttpContext.User.FindFirst("IDUSUARIO") != null)
            {
                return RedirectToAction("MenuEquipo", "Equipos");
            }

            if (usuario.Count() > 16)
            {
                ViewData["ERROR"] = "ERROR: EL NOMBRE DE USUARIO NO PUEDE TENER MAS DE 16 CARACTERES";

            }else if (await this.service.CompruebaNombre(usuario))
            {
                ViewData["ERROR"] = "ERROR: EL NOMBRE DE USUARIO INTRODUCIDO YA EXISTE";
            }
            else if (await this.service.CompruebaCorreo(correo))
            {
                ViewData["ERROR"] = "ERROR: EL CORREO ELECTRONICO INTRODUCIDO YA EXISTE";
            }
            else if (await this.service.CompruebaTelefono(telefono))
            {
                ViewData["ERROR"] = "ERROR: EL TELEFONO INTRODUCIDO YA EXISTE";
            }
            else if (contrasenha.Count() <= 8)
            {
                ViewData["ERROR"] = "ERROR: LA CONTRASEÑA DEBE TENER UN MINIMO DE 8 CARACTERES";
            }

            if (ViewData["ERROR"] != null)
            {
                return View();
            }
            else
            {
                await this.service.InsertUsuario(new Usuario
                {
                    IdUsuario = 0,
                    Nombre = usuario,
                    Contrasenia = contrasenha,
                    Correo = correo,
                    Telefono = telefono,
                    Token = "SIN TOKEN"
                });
                TempData["MENSAJE"] = "Usuario registrado correctamente";
                return RedirectToAction("InicioSesion");
            }
        }

        [AuthorizeUsers]
        public async Task<IActionResult> CerrarSesion()
        {
            HttpContext.Session.Remove("TOKEN");
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("InicioSesion");
        }

    }
}

F2GTraining/Views/Equipos/CrearEquipo.cshtml
@{
    Usuario user = Context.Session.GetObject<Usuario>("USUARIO");

    string controllerNewTeam = "Equipos";
    string actionNewTeam = "CrearEquipo";
}

@section CSSLinks{
    <link rel="stylesheet" href="~/css/registroequipo.css" asp-append-version="true" />
}

@section ZonaLogueo{
    <div class="user-section">
        <p>@Context.User.Identity.Name</p>
        <a asp-controller="Usuarios" asp-action="CerrarSesion">Cerrar sesion</a>
    </div>
}

@section Scripts{
    <script src="~/js/registroequipo.js" asp-append-version="true"></script>
}

    <form method="post" enctype="multipart/form-data">
        <div class="form-new-team">
            <div class="input-zone">
                <label>NOMBRE DE EQUIPO</label>
                <input type="text" name="nombre" required />
            </div>
            <div class="input-zone">
                <label>
                    SELECCIONAR IMAGEN
                    <input id="inputimagen" type="file" name="imagen" onchange="muestraArchivoSubido()" required />
                </label>
            </div>
        </div>
        <div class="check-zone">
            @if (ViewData["ERROR"] != null)
        {
            <p id="image-info" style="color: red">@ViewData["ERROR"]</p>
        }
        else
        {
                //INTENTAR PONER RECOMENDACION AQUI
            @*<p style="color: yellowgreen">Recomendamos subir logos de imagen con formato .png transparente y de mismo ancho y altura para una mayor experiencia visual</p>*@
            <p id="image-info">Para registrar el equipo, selecciona una imagen (Formatos: .png, .jpg, .jpeg)</p>
        }
    </div>
    <button type="submit">CREAR EQUIPO</button>
    <button class="back-button" type="button" onclick="vuelveInicio()">VOLVER</button>
</form>

F2GTraining/Views/Equipos/MenuEquipo.cshtml
@model List<Equipo>

@section CSSLinks{
    <link rel="stylesheet" href="~/css/menuequipo.css" asp-append-version="true" />
}

@section ZonaLogueo{
    <div class="user-section">
        <p>@Context.User.Identity.Name</p>
        <a asp-controller="Usuarios" asp-action="CerrarSesion">Cerrar sesion</a>
    </div>
}

@section Scripts{
    <script>
        $(function() {
            esconderEquipos();         
        });
    </script>
    <script src="~/js/menuequipo.js" asp-append-version="true"></script>
}

<div class="teamview-menu">
    <p>@ViewData["NOSE"]</p>
    <div class="team-section">
        @if (Model != null)
        {
            //Cambiar valor de equipo (TODO EL EQUIPO) - OPCIONAL
            <input type="hidden" id="equiposeleccionado" value="@Model[0].IdEquipo"/>
            <p>Selección de equipo</p>
            <select id="selectorequipo" onchange="esconderEquipos()">
                @foreach (Equipo equipo in Model)
                {
                    <option value="@equipo.IdEquipo">@equipo.Nombre</option>
                }
            </select>
            <div id="datosequipo"></div>
        }
        else
        {
            <div class="newteam-container">
                <p class="info-newteam">PARA PODER USAR LA APLICACION NECESITAS REGISTRAR EQUIPOS</p>
                <p class="info-newteam">TODAVIA NO HAS CREADO NINGUN EQUIPO. PULSA PARA CREAR UN NUEVO EQUIPO</p>
                <button onclick="location.href='@Url.Action("CrearEquipo", "Equipos", new {})'">NUEVO EQUIPO</button>
            </div>   
        }
    </div>

    @if (Model != null)
    {
        <div class="player-section">
            <div class="border-section">
                <a asp-controller="Equipos" asp-action="NotasEquipo">
                    MIS NOTAS
                </a>
            </div>
            <!--DENTRO DE PLAYER-ZONE SE CREAN TODOS LOS JUGADORES DE ESE EQUIPO-->
            <div id="datosjugadores" class="player-zone">
                
            </div>
            <div class="border-section"></div>
        </div>
    }

</div>

F2GTraining/Views/Equipos/NotasEquipo.cshtml
@section Scripts{
    <script src="~/js/sweetalert2.js" asp-append-version="true"></script>
    <script src="~/js/listanotas.js" asp-append-version="true"></script>
}

@section CSSLinks {
    <link rel="stylesheet" href="~/css/sweetalert2.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/listaNotas.css" asp-append-version="true" />
}

@section ZonaLogueo{
    <div class="user-section">
        <p>@Context.User.Identity.Name</p>
        <a asp-controller="Usuarios" asp-action="CerrarSesion">Cerrar sesion</a>
    </div>
}

@{
    List<Nota> notas;

    if (ViewData["NOTAS"] != null)
    {
        notas = ViewData["NOTAS"] as List<Nota>;
    }
    else
    {
        notas = null;
    }
}

<div class="view-notes-zone">
    <div class="notes-title">
        <p>NOTAS DE ENTRENADOR</p>
    </div>
    <div class="notes-site">

        @if (notas != null && notas.Count > 0)
        {
            @foreach (Nota nota in notas)
            {
                <div class="note-name" onclick="muestraOpciones(@nota.Id)">
                    <span>@nota.titulo</span>
                </div>
                <div class="note-options" id="sessionopt-@nota.Id">
                    <p id="cuerpoNota">@nota.cuerpo</p>
                </div>
            }
        }
        else
        {
            <p class="no-notes">SIN NOTAS</p>
        }

    </div>
    <div class="border-notes"></div>
    <div class="button-zone">
        <button onclick="vuelveInicio()" class="back-button">VOLVER</button>
        <button onclick="listaNotas()" class="new-note">GUARDAR NOTA</button>
    </div>
</div>

<form id='form-new-nota' method="post">
    <input type="hidden" id="titulo" name="titulo">
    <input type="hidden" id="cuerpo" name="cuerpo">
</form>

F2GTraining/Views/Equipos/_PartialVistaEquipo.cshtml
@model Equipo

<div class="image-team" id="teamimage-@Model.IdEquipo">
    <img src="@Model.Imagen" />
</div>
<div class="link-team-actions" id="teamaction-@Model.IdEquipo">
    <a asp-controller="Entrenamientos" asp-action="ListaSesiones" asp-route-idequipo="@Model.IdEquipo" class="minibutton-teamview">SESIONES DE ENTRENAMIENTO</a>
    <a asp-controller="Jugadores" asp-action="CrearJugador" asp-route-idequipo="@Model.IdEquipo" class="minibutton-teamview">AÑADIR NUEVO JUGADOR</a>
    <a asp-controller="Equipos" asp-action="CrearEquipo" class="minibutton-teamview">NUEVO EQUIPO</a>
</div>